### ISSUE TITLE
Couldn't find package "react-native-inhibit-warnings" on the "npm" registry

### ISSUE THREAD

**Issue by KarolAltamirano** [mattijsf/react-native-inhibit-warnings#1]
I got an error when tried to install with `yarn` `Couldn't find package "react-native-inhibit-warnings" on the "npm" registry`. I know I can install it directly from github but also documentation is mentioning following command:
```
yarn add --dev react-native-inhibit-warnings
```
Just curious, is there a reason the package hasn't been published in npm?

**Comment by mattijsf** [comment]
Hi @KarolAltamirano, can you try again? It should be available now in npm.

**Comment by mattijsf** [comment]
There was no specific reason. Just forgot about it while I was personally also using the github reference. Thanks for the heads-up!

**Comment by KarolAltamirano** [comment]
@mattijsf thanks a lot for publishing it in npm!! All works now 👍
